# Exploratory Data Analysis

In [3]:
!pip install pandas_profiling
!pip install sweetviz

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
#load the libraries
import pandas as pd
import numpy as np
import pandas_profiling as pp
import sweetviz as sv

In [5]:
data1 = pd.read_csv("https://raw.githubusercontent.com/omgo101/dataset-/main/iris.csv")

In [6]:
data1

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  \
0             1           5.1          3.5           1.4          0.2   
1             2           4.9          3.0           1.4          0.2   
2             3           4.7          3.2           1.3          0.2   
3             4           4.6          3.1           1.5          0.2   
4             5           5.0          3.6           1.4          0.2   
..          ...           ...          ...           ...          ...   
145         146           6.7          3.0           5.2          2.3   
146         147           6.3          2.5           5.0          1.9   
147         148           6.5          3.0           5.2          2.0   
148         149           6.2          3.4           5.4          2.3   
149         150           5.9          3.0           5.1          1.8   

       Species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 6 columns]

In [7]:
data1.tail(10)

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  \
140         141           6.7          3.1           5.6          2.4   
141         142           6.9          3.1           5.1          2.3   
142         143           5.8          2.7           5.1          1.9   
143         144           6.8          3.2           5.9          2.3   
144         145           6.7          3.3           5.7          2.5   
145         146           6.7          3.0           5.2          2.3   
146         147           6.3          2.5           5.0          1.9   
147         148           6.5          3.0           5.2          2.0   
148         149           6.2          3.4           5.4          2.3   
149         150           5.9          3.0           5.1          1.8   

       Species  
140  virginica  
141  virginica  
142  virginica  
143  virginica  
144  virginica  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica

In [8]:
data1

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  \
0             1           5.1          3.5           1.4          0.2   
1             2           4.9          3.0           1.4          0.2   
2             3           4.7          3.2           1.3          0.2   
3             4           4.6          3.1           1.5          0.2   
4             5           5.0          3.6           1.4          0.2   
..          ...           ...          ...           ...          ...   
145         146           6.7          3.0           5.2          2.3   
146         147           6.3          2.5           5.0          1.9   
147         148           6.5          3.0           5.2          2.0   
148         149           6.2          3.4           5.4          2.3   
149         150           5.9          3.0           5.1          1.8   

       Species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 6 columns]

In [9]:
#Data Structure 
type(data1)
data1.shape

(150, 6)

In [10]:
#data types
data1.dtypes

Unnamed: 0        int64
Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species          object
dtype: object

# Duplicates

In [11]:
#Count of duplicated rows
data1[data1.duplicated()].shape

(0, 6)

In [12]:
data1

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  \
0             1           5.1          3.5           1.4          0.2   
1             2           4.9          3.0           1.4          0.2   
2             3           4.7          3.2           1.3          0.2   
3             4           4.6          3.1           1.5          0.2   
4             5           5.0          3.6           1.4          0.2   
..          ...           ...          ...           ...          ...   
145         146           6.7          3.0           5.2          2.3   
146         147           6.3          2.5           5.0          1.9   
147         148           6.5          3.0           5.2          2.0   
148         149           6.2          3.4           5.4          2.3   
149         150           5.9          3.0           5.1          1.8   

       Species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 6 columns]

In [13]:
#Print the duplicated rows
data1[data1.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, Species]
Index: []

# Rename the columns

In [14]:
#rename the Solar column
data = data1.rename({'Sepal.Length': 'SepalLength','Sepal.Width':'SepalWidth','Petal.Length':'PetalLength','Petal.Width':'PetalWidth'}, axis=1)

In [15]:
data

Unnamed: 0  SepalLength  SepalWidth  PetalLength  PetalWidth    Species
0             1          5.1         3.5          1.4         0.2     setosa
1             2          4.9         3.0          1.4         0.2     setosa
2             3          4.7         3.2          1.3         0.2     setosa
3             4          4.6         3.1          1.5         0.2     setosa
4             5          5.0         3.6          1.4         0.2     setosa
..          ...          ...         ...          ...         ...        ...
145         146          6.7         3.0          5.2         2.3  virginica
146         147          6.3         2.5          5.0         1.9  virginica
147         148          6.5         3.0          5.2         2.0  virginica
148         149          6.2         3.4          5.4         2.3  virginica
149         150          5.9         3.0          5.1         1.8  virginica

[150 rows x 6 columns]

# Missing Values and Imputation

In [16]:
data[data.isnull().any(axis=1)].head()

Empty DataFrame
Columns: [Unnamed: 0, SepalLength, SepalWidth, PetalLength, PetalWidth, Species]
Index: []

In [17]:
data.isnull().sum()

Unnamed: 0     0
SepalLength    0
SepalWidth     0
PetalLength    0
PetalWidth     0
Species        0
dtype: int64

# Correlation analysis

In [18]:
data.corr()

Unnamed: 0  SepalLength  SepalWidth  PetalLength  PetalWidth
Unnamed: 0     1.000000     0.716676   -0.402301     0.882637    0.900027
SepalLength    0.716676     1.000000   -0.117570     0.871754    0.817941
SepalWidth    -0.402301    -0.117570    1.000000    -0.428440   -0.366126
PetalLength    0.882637     0.871754   -0.428440     1.000000    0.962865
PetalWidth     0.900027     0.817941   -0.366126     0.962865    1.000000

# Transformations

#### Dummy Variable

In [19]:
#Creating dummy variable for Weather column
data=pd.get_dummies(data,columns=['Species'])

In [20]:
data

Unnamed: 0  SepalLength  SepalWidth  PetalLength  PetalWidth  \
0             1          5.1         3.5          1.4         0.2   
1             2          4.9         3.0          1.4         0.2   
2             3          4.7         3.2          1.3         0.2   
3             4          4.6         3.1          1.5         0.2   
4             5          5.0         3.6          1.4         0.2   
..          ...          ...         ...          ...         ...   
145         146          6.7         3.0          5.2         2.3   
146         147          6.3         2.5          5.0         1.9   
147         148          6.5         3.0          5.2         2.0   
148         149          6.2         3.4          5.4         2.3   
149         150          5.9         3.0          5.1         1.8   

     Species_setosa  Species_versicolor  Species_virginica  
0                 1                   0                  0  
1                 1                   0                  0  
2                 1                   0                  0  
3                 1                   0                  0  
4                 1                   0                  0  
..              ...                 ...                ...  
145               0                   0                  1  
146               0                   0                  1  
147               0                   0                  1  
148               0                   0                  1  
149               0                   0                  1  

[150 rows x 8 columns]

In [21]:
data_cleaned4=data.dropna()

#### Normalization of the data

In [22]:
#Normalization of the data
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

In [23]:
data_cleaned4.values

array([[  1. ,   5.1,   3.5, ...,   1. ,   0. ,   0. ],
       [  2. ,   4.9,   3. , ...,   1. ,   0. ,   0. ],
       [  3. ,   4.7,   3.2, ...,   1. ,   0. ,   0. ],
       ...,
       [148. ,   6.5,   3. , ...,   0. ,   0. ,   1. ],
       [149. ,   6.2,   3.4, ...,   0. ,   0. ,   1. ],
       [150. ,   5.9,   3. , ...,   0. ,   0. ,   1. ]])

In [24]:
array = data.values

scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(array[:,0:5])

#transformed data
set_printoptions(precision=2)
print(rescaledX[0:5,:])


[[0.   0.22 0.62 0.07 0.04]
 [0.01 0.17 0.42 0.07 0.04]
 [0.01 0.11 0.5  0.05 0.04]
 [0.02 0.08 0.46 0.08 0.04]
 [0.03 0.19 0.67 0.07 0.04]]


In [25]:
# Standardize data (0 mean, 1 stdev)
from sklearn.preprocessing import StandardScaler

In [26]:
array = data_cleaned4.values
scaler = StandardScaler().fit(array)
rescaledX = scaler.transform(array)

# summarize transformed data
set_printoptions(precision=2)
print(rescaledX[0:5,:])

[[-1.72 -0.9   1.02 -1.34 -1.32  1.41 -0.71 -0.71]
 [-1.7  -1.14 -0.13 -1.34 -1.32  1.41 -0.71 -0.71]
 [-1.67 -1.39  0.33 -1.4  -1.32  1.41 -0.71 -0.71]
 [-1.65 -1.51  0.1  -1.28 -1.32  1.41 -0.71 -0.71]
 [-1.63 -1.02  1.25 -1.34 -1.32  1.41 -0.71 -0.71]]


# Speed up the EDA process

In [27]:
!pip install pandas-profiling==2.7.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [28]:
EDA_report= pp.ProfileReport(data)
EDA_report.to_file(output_file='report.html')

Summarize dataset:   0%|          | 0/20 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [29]:
sweet_report = sv.analyze(data)
sweet_report.show_html('weather_report.html')

                                             |          | [  0%]   00:00 -> (? left)

Report weather_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.
